# docker/Dockerfile.inference

FROM nvidia/cuda:12.8.1-runtime-ubuntu22.04

WORKDIR /workspace/virtue-multimodal

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3.10 python3.10-venv python3-pip libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

RUN python3.10 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY . .

RUN pip install --upgrade pip && \
    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 && \
    pip install -r requirements-docker.txt

EXPOSE 8000

CMD ["python", "scripts/inference/api_server.py"]
